In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# Merge

In [4]:
dframe = DataFrame({'key':['X', 'Z', 'Y', 'Z', 'X', 'X'], 'data_set_1':np.arange(6)})
dframe

data_set_1 key
0           0   X
1           1   Z
2           2   Y
3           3   Z
4           4   X
5           5   X

In [7]:
dframe1 = DataFrame({'key':['Q', 'Y', 'Z'], 'data_set_2':[1, 2, 3]})
dframe1

data_set_2 key
0           1   Q
1           2   Y
2           3   Z

In [8]:
# match same key and drops non-matching keys
pd.merge(dframe, dframe1)

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [9]:
# same as above
pd.merge(dframe, dframe1, on = 'key')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2

In [10]:
# use left dataframes keys and values, fills NaN for keyws with no values
pd.merge(dframe, dframe1, on = 'key', how = 'left')

data_set_1 key  data_set_2
0           0   X         NaN
1           1   Z           3
2           2   Y           2
3           3   Z           3
4           4   X         NaN
5           5   X         NaN

In [11]:
pd.merge(dframe, dframe1, on = 'key', how = 'right')

data_set_1 key  data_set_2
0           1   Z           3
1           3   Z           3
2           2   Y           2
3         NaN   Q           1

In [12]:
# union of keys / all keys
pd.merge(dframe, dframe1, on = 'key', how = 'outer')

data_set_1 key  data_set_2
0           0   X         NaN
1           4   X         NaN
2           5   X         NaN
3           1   Z           3
4           3   Z           3
5           2   Y           2
6         NaN   Q           1

In [13]:
dframe2 = DataFrame({'key':['X', 'X', 'X', 'Y', 'Z', 'Z'], 'data_set_3':range(6)})
dframe2

data_set_3 key
0           0   X
1           1   X
2           2   X
3           3   Y
4           4   Z
5           5   Z

In [15]:
dframe3 = DataFrame({'key':['Y', 'Y', 'X', 'X', 'Z'], 'data_set_4':range(5)})
dframe3

data_set_4 key
0           0   Y
1           1   Y
2           2   X
3           3   X
4           4   Z

In [17]:
pd.merge(dframe2, dframe3)

data_set_3 key  data_set_4
0           0   X           2
1           0   X           3
2           1   X           2
3           1   X           3
4           2   X           2
5           2   X           3
6           3   Y           0
7           3   Y           1
8           4   Z           4
9           5   Z           4

In [18]:
# merge with multiple keys
df_left = DataFrame({'key1':['SF', 'SF', 'LA'],
                     'key2':['one', 'two', 'one'],
                     'left_data':[10, 20, 30]})

df_right = DataFrame({'key1':['SF', 'SF', 'LA', 'LA'],
                     'key2':['one', 'one', 'one', 'two'],
                     'right_data':[40, 50, 60, 70]})

df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [19]:
df_right

key1 key2  right_data
0   SF  one          40
1   SF  one          50
2   LA  one          60
3   LA  two          70

In [21]:
# hold both keys constant
pd.merge(df_left, df_right, on = ['key1', 'key2'], how = 'outer')

key1 key2  left_data  right_data
0   SF  one         10          40
1   SF  one         10          50
2   SF  two         20         NaN
3   LA  one         30          60
4   LA  two        NaN          70

In [22]:
# keeps key2 separate
pd.merge(df_left, df_right, on = 'key1')

key1 key2_x  left_data key2_y  right_data
0   SF    one         10    one          40
1   SF    one         10    one          50
2   SF    two         20    one          40
3   SF    two         20    one          50
4   LA    one         30    one          60
5   LA    one         30    two          70

In [23]:
# names the keys / adds suffixes
pd.merge(df_left, df_right, on = 'key1', suffixes = ('_lefty', '_righty'))

key1 key2_lefty  left_data key2_righty  right_data
0   SF        one         10         one          40
1   SF        one         10         one          50
2   SF        two         20         one          40
3   SF        two         20         one          50
4   LA        one         30         one          60
5   LA        one         30         two          70

Check the merge method in the pandas documentation for more info.

# Merge on Index

In [24]:
df_l = DataFrame({'key':['X', 'Y', 'Z', 'X', 'Y'],
                  'data':range(5)})
df_l

data key
0     0   X
1     1   Y
2     2   Z
3     3   X
4     4   Y

In [26]:
df_r = DataFrame({'group_data':[10, 20]}, index = ['X', 'Y'])
df_r

group_data
X          10
Y          20

In [27]:
# filled 10 and 20 twice based on key
pd.merge(df_l, df_r, left_on = 'key', right_index = True)

data key  group_data
0     0   X          10
3     3   X          10
1     1   Y          20
4     4   Y          20

In [31]:
df_l_hr = DataFrame({'key1':['SF', 'SF', 'SF', 'LA', 'LA'],
                     'key2':[10, 20, 30, 20, 30],
                     'data_set':np.arange(5.)})
df_l_hr

data_set key1  key2
0         0   SF    10
1         1   SF    20
2         2   SF    30
3         3   LA    20
4         4   LA    30

In [34]:
df_r_hr = DataFrame(np.arange(10).reshape(5, 2),
                    index = [['LA', 'LA', 'SF', 'SF', 'SF'], [20, 10, 10, 10, 20]],
                   columns = ['col_1', 'col_2'])
df_r_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [35]:
pd.merge(df_l_hr, df_r_hr, left_on = ['key1', 'key2'], right_index = True)

data_set key1  key2  col_1  col_2
0         0   SF    10      4      5
0         0   SF    10      6      7
1         1   SF    20      8      9
3         3   LA    20      0      1

In [36]:
df_l.join(df_r)

data key  group_data
0     0   X         NaN
1     1   Y         NaN
2     2   Z         NaN
3     3   X         NaN
4     4   Y         NaN

# Concatenate

In [37]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
# add array on column axis
np.concatenate([arr, arr], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [39]:
# add array on row axis
np.concatenate([arr, arr], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
ser = Series([0, 1, 2], index = ['T', 'U', 'V'])

ser1 = Series([3, 4], index = ['X', 'Y'])

ser

T    0
U    1
V    2
dtype: int64

In [41]:
ser1

X    3
Y    4
dtype: int64

In [42]:
# creates a Series
pd.concat([ser, ser1])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [43]:
# creates a dataframe missing information
pd.concat([ser, ser1], axis = 1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [44]:
# name Series in hierarchical index
pd.concat([ser, ser1], keys = ['cat', 'cat1'])

cat   T    0
      U    1
      V    2
cat1  X    3
      Y    4
dtype: int64

In [45]:
dframe4 = DataFrame(np.random.randn(4, 3), columns = ['X', 'Y', 'Z'])
dframe5 = DataFrame(np.random.randn(3, 3), columns = ['Y', 'Q', 'X'])

dframe4

X         Y         Z
0  0.019396  0.027642 -2.206557
1 -0.275737 -0.240567  1.453850
2 -0.275222  1.003408 -0.817542
3  0.776094 -0.664685 -0.695637

In [46]:
dframe5

Y         Q         X
0 -0.349348 -0.751563  2.384292
1  1.145179 -0.171137 -0.415641
2 -0.392359  0.661856 -1.788102

In [47]:
# keeps index information and fills NaN for missing values
pd.concat([dframe4, dframe5])

Q         X         Y         Z
0       NaN  0.019396  0.027642 -2.206557
1       NaN -0.275737 -0.240567  1.453850
2       NaN -0.275222  1.003408 -0.817542
3       NaN  0.776094 -0.664685 -0.695637
0 -0.751563  2.384292 -0.349348       NaN
1 -0.171137 -0.415641  1.145179       NaN
2  0.661856 -1.788102 -0.392359       NaN

In [48]:
# ignore index to receive continuous index
pd.concat([dframe4, dframe5], ignore_index = True)

Q         X         Y         Z
0       NaN  0.019396  0.027642 -2.206557
1       NaN -0.275737 -0.240567  1.453850
2       NaN -0.275222  1.003408 -0.817542
3       NaN  0.776094 -0.664685 -0.695637
4 -0.751563  2.384292 -0.349348       NaN
5 -0.171137 -0.415641  1.145179       NaN
6  0.661856 -1.788102 -0.392359       NaN

# Combining DataFrames

In [49]:
ser2 = Series([2, np.nan, 4, np.nan, 6, np.nan],
              index = ['Q', 'R', 'S', 'T', 'U', 'V'])
ser2

Q     2
R   NaN
S     4
T   NaN
U     6
V   NaN
dtype: float64

In [50]:
ser3 = Series(np.arange(len(ser2)), dtype = np.float64,
              index = ['Q', 'R', 'S', 'T', 'U', 'V'])
ser3

Q    0
R    1
S    2
T    3
U    4
V    5
dtype: float64

In [51]:
# where there is a null arguement in ser2, put ser3 value, else put ser2 value
# keep ser2 index
Series(np.where(pd.isnull(ser2), ser3, ser2), index = ser2.index)

Q    2
R    1
S    4
T    3
U    6
V    5
dtype: float64

In [53]:
# same thing
ser2.combine_first(ser3)

Q    2
R    1
S    4
T    3
U    6
V    5
dtype: float64

In [55]:
nan = np.nan

dframe_odds = DataFrame({'X':[1., nan, 3., nan],
                        'Y':[nan, 5., nan, 7.],
                        'Z':[nan, 9., nan, 11]})

dframe_evens = DataFrame({'X':[2., 4., nan, 6., 8.],
                        'Y':[nan, 10., 12., 14., 16.]})

dframe_odds

X   Y   Z
0   1 NaN NaN
1 NaN   5   9
2   3 NaN NaN
3 NaN   7  11

In [56]:
dframe_evens

X   Y
0   2 NaN
1   4  10
2 NaN  12
3   6  14
4   8  16

In [57]:
# takes dframe_odds and where there's a null value passes dframe_evens
dframe_odds.combine_first(dframe_evens)

X   Y   Z
0  1 NaN NaN
1  4   5   9
2  3  12 NaN
3  6   7  11
4  8  16 NaN

# Reshaping

In [58]:
dframe6 = DataFrame(np.arange(8).reshape(2, 4),
                    index = pd.Index(['LA', 'SF'], name = 'City'),
                   columns = pd.Index(['A', 'B', 'C', 'D'], name = 'letter'))
dframe6

letter  A  B  C  D
City              
LA      0  1  2  3
SF      4  5  6  7

In [59]:
# stack into hierarchy
dframe_st = dframe6.stack()
dframe_st

City  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int64

In [60]:
# back to dataframe
dframe_st.unstack()

letter  A  B  C  D
City              
LA      0  1  2  3
SF      4  5  6  7

In [61]:
# same because letter was default
dframe_st.unstack('letter')

letter  A  B  C  D
City              
LA      0  1  2  3
SF      4  5  6  7

In [63]:
# unstack by city
dframe_st.unstack('City')

City    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [64]:
ser4 = Series([0, 1, 2], index = ['Q', 'X', 'Y'])
ser5 = Series([4, 5, 6], index = ['X', 'Y', 'Z'])

dframe7 = pd.concat([ser4, ser5], keys = ['Alpha', 'Beta'])
dframe7

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [65]:
dframe7.unstack()

Q  X  Y   Z
Alpha   0  1  2 NaN
Beta  NaN  4  5   6

In [66]:
# no null values
dframe7.unstack().stack()

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: float64

In [68]:
# keep null values from dataframe
dframe8 = dframe7.unstack().stack(dropna = False)
dframe8

Alpha  Q     0
       X     1
       Y     2
       Z   NaN
Beta   Q   NaN
       X     4
       Y     5
       Z     6
dtype: float64

# Pivoting

You can copy his code, but it's outside the scope of the course.

# Duplicates in DataFrames

In [69]:
dframe9 = DataFrame({'key1':['A']*2 + ['B']*3,
                    'key2':[2, 2, 2, 3, 3]})
dframe9

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [70]:
# true for each row that, from top to bottom, have been duplicated
dframe9.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [71]:
# get rid of the duplicates
dframe9.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [72]:
# drop duplicates based on key1
dframe9.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [75]:
# keep the last duplicate found based on key1
dframe9.drop_duplicates(['key1'], keep = 'last')

key1  key2
1    A     2
4    B     3

# Mapping

In [76]:
dframe10 = DataFrame({'city':['Alma', 'Bryan Head', 'Fox Park'],
                    'altitude':[3158, 3000, 2762,]})
dframe10

altitude        city
0      3158        Alma
1      3000  Bryan Head
2      2762    Fox Park

In [78]:
state_map = {'Alma': 'Colorado', 'Bryan Head':'Utah', 'Fox Park':'Wyoming'}

# add a new column using a dictionary
dframe10['state'] = dframe10['city'].map(state_map)
dframe10

altitude        city     state
0      3158        Alma  Colorado
1      3000  Bryan Head      Utah
2      2762    Fox Park   Wyoming

# Replace

In [79]:
ser6 = Series([1, 2, 3, 4, 1, 2, 3, 4])
ser6

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [80]:
# every value 1 is replaced with NaN
ser6.replace(1, np.nan)

0   NaN
1     2
2     3
3     4
4   NaN
5     2
6     3
7     4
dtype: float64

In [81]:
# every value in your first list is replaced by every value in second list
ser6.replace([1, 4], [100, 400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [82]:
# replace key with its value
ser6.replace({4:np.nan})

0     1
1     2
2     3
3   NaN
4     1
5     2
6     3
7   NaN
dtype: float64

# Rename Index

In [84]:
dframe11 = DataFrame(np.arange(12).reshape(3, 4),
                    index = ['NY', 'LA', 'SF'],
                    columns = ['A', 'B', 'C', 'D'])
dframe11

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [85]:
# makes all index letters lowercase
dframe11.index.map(str.lower)

array(['ny', 'la', 'sf'], dtype=object)

In [86]:
# save the change
dframe11.index = dframe11.index.map(str.lower)
dframe11

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [87]:
# title capitalizes first letter, lowercase columns
dframe11.rename(index = str.title, columns = str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [89]:
# rename text
dframe11.rename(index = {'ny':'NEW YORK'},
               columns = {'A':'ALPHA'})

ALPHA  B   C   D
NEW YORK      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [92]:
# save change
dframe11.rename(index = {'ny':'NEW YORK'},
               columns = {'A':'ALPHA'},
               inplace = True)
dframe11

ALPHA  B   C   D
NEW YORK      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

# Binning

In [94]:
year = [1990, 1991, 1992, 2008, 2012, 2015, 1987, 1969, 2013, 2008, 1999]

decade_bins = [1960, 1970, 1980, 1990, 2000, 2010, 2020]

# use cut to cut object based on bins
decade_cat = pd.cut(year, decade_bins)
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, object): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [95]:
decade_cat.categories

Index([u'(1960, 1970]', u'(1970, 1980]', u'(1980, 1990]', u'(1990, 2000]',
       u'(2000, 2010]', u'(2010, 2020]'],
      dtype='object')

In [96]:
# check value counts in each category
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [97]:
# cuts up bins into two
# ( = open, ] = closed
pd.cut(year, 2, precision = 1)

[(1969, 1992], (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], ..., (1969, 1992], (1969, 1992], (1992, 2015], (1992, 2015], (1992, 2015]]
Length: 11
Categories (2, object): [(1969, 1992] < (1992, 2015]]

# Outliers

In [98]:
# seeded our random generator
np.random.seed(12345)

In [100]:
dframe12 = DataFrame(np.random.randn(1000,4))
dframe12.head()

0         1         2         3
0  1.150765 -0.997174  0.046486 -0.610441
1 -0.394982  1.199915 -0.451814 -0.155385
2 -0.153514  0.011194 -0.050555  0.420211
3  1.190981  1.561488 -1.132925  0.097083
4 -1.031573 -0.044618 -0.218153  0.772942

In [101]:
dframe12.tail()

0         1         2         3
995 -0.805171  0.976343  0.859475  0.203516
996 -0.064420  0.487940  1.353146  0.291152
997 -0.051474  1.353153  1.066038  1.260350
998 -0.144072 -1.074131 -0.245138  1.474357
999 -0.741705 -0.462397 -0.419776  0.592210

In [102]:
dframe12.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020880     0.001643    -0.019453    -0.026122
std       0.980023     1.025441     0.995088     0.960486
min      -3.108915    -3.645860    -3.481593    -3.194414
25%      -0.697479    -0.697678    -0.694020    -0.700987
50%      -0.005279     0.031774    -0.014728    -0.038483
75%       0.618116     0.690065     0.651287     0.649747
max       2.859053     3.189940     3.525865     3.023720

In [104]:
col = dframe12[0]

col.head()

0    1.150765
1   -0.394982
2   -0.153514
3    1.190981
4   -1.031573
Name: 0, dtype: float64

In [105]:
# show me where absolute value of row is greater than 3
col[np.abs(col) > 3]

396   -3.108915
Name: 0, dtype: float64

In [107]:
# return any row with value that has |3| > 3
dframe12[(np.abs(dframe12) > 3).any(1)]

0         1         2         3
46  -0.658090 -0.207434  3.525865  0.283070
67   0.599947 -3.645860  0.255475 -0.549574
289 -1.559625  0.336788 -3.333767 -1.240685
371 -1.116332 -3.018842 -0.298748  0.406954
396 -3.108915  1.117755 -0.152780 -0.340173
526  1.188742 -3.183867  1.050471 -1.042736
573 -2.214074 -3.140963 -1.509976 -0.389818
738 -0.088202  1.090038 -0.848098 -3.194414
768  0.474358  0.003349 -0.011807  3.023720
797  2.368010  0.452649 -3.481593  0.789944
966  0.164293  3.082067 -0.516982  0.251909
994 -0.843849  3.189940  0.070978  0.516982

In [110]:
# if |value| > 3 set equal to sign of value times 3
# nothing greater than 3 or lower than -1, capping outliers
dframe12[np.abs(dframe12) > 3] = np.sign(dframe12) * 3

dframe12.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.020772     0.002361    -0.019163    -0.025951
std       0.979685     1.021487     0.990725     0.959788
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.697479    -0.697678    -0.694020    -0.700987
50%      -0.005279     0.031774    -0.014728    -0.038483
75%       0.618116     0.690065     0.651287     0.649747
max       2.859053     3.000000     3.000000     3.000000

# Permutations

In [111]:
dframe13 = DataFrame(np.arange(16).reshape(4, 4))

# from 0 - 3 blender will create a random permutation of it
blender = np.random.permutation(4)
blender

array([2, 3, 0, 1])

In [112]:
dframe13

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [113]:
# take index blender has created
dframe13.take(blender)

0   1   2   3
2   8   9  10  11
3  12  13  14  15
0   0   1   2   3
1   4   5   6   7

In [115]:
box = np.array([1, 2, 3])

# permutation with replacement
shaker = np.random.randint(0, len(box), size = 10)
shaker

array([2, 1, 2, 0, 2, 1, 0, 2, 0, 0])

In [116]:
hand_grabs = box.take(shaker)
hand_grabs

array([3, 2, 3, 1, 3, 2, 1, 3, 1, 1])